version: '3'

services:
    web:
        image: github.com/erikfogelstrand/tvmannen:latest
        #ports:
        #    - "4001:4001"
        command: uwsgi --enable-threads --http :4001 --module tv:app
        volumes:
            - images:/src/static/pr

volumes:
    images:

